from src.preferences.templates.template import (
    REVEALED_CHOICE_TEMPLATE,
    REVEALED_COMPLETION_TEMPLATE,
    REVEALED_PLACEHOLDERS,
    POST_TASK_STATED_PLACEHOLDERS,
    POST_TASK_STATED_TEMPLATE,
    POST_TASK_REVEALED_PLACEHOLDERS,
    POST_TASK_REVEALED_TEMPLATE,
    PRE_TASK_STATED_PLACEHOLDERS,
    PRE_TASK_STATED_TEMPLATE,
    TEMPLATE_TYPE_PLACEHOLDERS,
    PromptTemplate,
    revealed_template,
    load_templates_from_yaml,
    post_task_stated_template,
    post_task_revealed_template,
    pre_task_stated_template,
)
from src.preferences.templates.builders import (
    RevealedPromptBuilder,
    PostTaskStatedPromptBuilder,
    PostTaskRevealedPromptBuilder,
    PreTaskStatedPromptBuilder,
    PromptBuilder,
)
from src.preferences.templates.generator import (
    GeneratorConfig,
    TemplateVariant,
    generate_and_write,
    generate_templates,
    load_config_from_yaml,
    write_templates_yaml,
)

__all__ = [
    # Template
    "REVEALED_CHOICE_TEMPLATE",
    "REVEALED_COMPLETION_TEMPLATE",
    "REVEALED_PLACEHOLDERS",
    "POST_TASK_STATED_PLACEHOLDERS",
    "POST_TASK_STATED_TEMPLATE",
    "POST_TASK_REVEALED_PLACEHOLDERS",
    "POST_TASK_REVEALED_TEMPLATE",
    "PRE_TASK_STATED_PLACEHOLDERS",
    "PRE_TASK_STATED_TEMPLATE",
    "TEMPLATE_TYPE_PLACEHOLDERS",
    "PromptTemplate",
    "revealed_template",
    "load_templates_from_yaml",
    "post_task_stated_template",
    "post_task_revealed_template",
    "pre_task_stated_template",
    # Builders
    "RevealedPromptBuilder",
    "PostTaskStatedPromptBuilder",
    "PostTaskRevealedPromptBuilder",
    "PreTaskStatedPromptBuilder",
    "PromptBuilder",
    # Generator
    "GeneratorConfig",
    "TemplateVariant",
    "generate_and_write",
    "generate_templates",
    "load_config_from_yaml",
    "write_templates_yaml",
]
